name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install PHP Dependencies
      uses: php-actions/composer@v6

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build Admin
      uses: borales/actions-yarn@v4

    - name: Deploy WordPress Plugin
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: twicpics
